title: ångstromCTF Learn
email: contact@angstromctf.com
description: >
  A collection of learning materials for cybersecurity and computer science.
  Learn about breaking codes, hacking websites, exploiting programs, and more!
  For middle school and high school students.
baseurl: ""
url: "learn.angstromctf.com"
twitter_username: angstromctf
github_username:  angstromctf

collections:
  modules:
    output: true

defaults:
  - scope:
      path: ""
      type: modules
    values:
      layout: module
      permalink: /modules/:path/

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
